// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwxblkgnyneqwotlsqss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3eGJsa2dueW5lcXdvdGxzcXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5Mzg2MDMsImV4cCI6MjA1NTUxNDYwM30.d0o5w0-49pPmzK1AJdLL6eD4yCNIWWrIvHP5SimkLf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);